apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.AppName}}
  name: {{.Values.AppName}}
  namespace: {{.Values.namespace.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      tag: {{.Values.tag}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        tag: {{.Values.tag}}
    spec:
      containers:
      - image: {{.Values.image}}:{{.Values.tag}}
        imagePullPolicy: {{.Values.pullPolicy}}
        name: {{.Values.AppName}}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.livenessProbe.port }}
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.readinessProbe.port }}
          initialDelaySeconds: 30
          periodSeconds: 3
