apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: techtrend
  name: techtrends
  namespace: {{.Values.namespace}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      tag: {{.Values.tag}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        tag: {{.Values.tag}}
    spec:
      containers:
      - image: {{.Values.image}}:{{.Values.tag}}
        imagePullPolicy: {{.Values.pullPolicy}}
        name: techtrend
        - containerPort: 3112
          protocol: TCP
        livelnessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 3112
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 3112
          initialDelaySeconds: 10
          periodSeconds: 5s
