apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: techtrend
  name: techtrends
  namespace: {{.Values.namespace}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      tag: {{.Values.tag}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        tag: {{.Values.tag}}
    spec:
      containers:
      - image: {{.Values.image}}:{{.Values.tag}}
        imagePullPolicy: {{.Values.pullPolicy}}
        name: techtrends
