apiVersion: v1
kind: Service
metadata:
  labels:
    tag: {{.Values.tag}}
  name: techtrends
  namespace: {{.Values.namespace}}
spec:
  ports:
  - port: {{.Values.service_port}}
    protocol: TCP
    targetPort: {{.Values.service_target_port}}
  selector:
    tag: {{.Values.tag}}
  type: {{.Values.service_type}}
