apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: kzouhar/techtrends:1.0
        imagePullPolicy: IfNotPresent
        name: techtrends
        ports:
          - containerPort: 3111
            protocol: TCP
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 3111
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 3111
          initialDelaySeconds: 10
          periodSeconds: 5
