AppName: techtrends
namespace: 
  name: sandbox
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
image: kzouhar/techtrends
tag: latest
pullPolicy: IfNotPresent
replicaCount: 1
requests:
  memory: 64Mi
  cpu: 250m
limit:
  memory: 128Mi
limit:
  cpu:  500m
containerPort: 3111
readinessProbe:
   path: /healthz
   port: 3112
livenessProbe:
   path: /healthz
   port: 3112
