namespace: sandbox
service_port: 4111
service_target_port: 3111
service_protocol: TCP
type: ClusterIP
image: techtrends
tag: latest
pullPolicy: IfNotPresent
replicaCount: 1
requests_memory: 64Mi
request_cpu: 250m
limit_memory: 128Mi
limit_cpu:  500m
containerPort: 3111
liveness_probe_path: /healthz
readiness_probe_path: /healthz
